### ISSUE TITLE
`man e` command fails to render README on projects without src directory

### ISSUE THREAD

**Issue by robinraju** [eloots/course-management-tools#108]
`man e` command fails to render the `README` on individual exercises on a master repository.
This happens on projects without an `src` directory (Play Framework)

**Comment by eloots** [comment]
@robinraju I think this can be closed now as it is resolved in the different course templates (via #109), isn't it?

**Comment by robinraju** [comment]
FIxed in f656cf8c9e5b0140c95df45ac32ddfd0294d7cc0

**Comment by robinraju** [comment]
`man e` command seems not working on a `linearized` repo.

**Aadditional Info:** 
The fix was not applied on `sbtLinearizeCommands/Man.scala.template`

**Comment by robinraju** [comment]
Fixed in da5e8f9fcf8feabcec306a15f994675bf6e4267c
