### ISSUE TITLE
SBT shellPrompt fails to render on Play projects

### ISSUE THREAD

**Issue by robinraju** [eloots/course-management-tools#110]
Course management Tools customize sbt prompt through `StudentCommandsPlugin`

The following shell prompt is generated usually.
```
man [e] > Course Name > exercise name >
```
`StudentCommandsPlugin` fails to generate the shell prompt if used along with projects already set `shellPromt` using their own sbt plugin. 
`Play Framework` is an example, it uses its own sbt shell prompt.

**Comment by robinraju** [comment]
This could be fixed using the solution described in the following issue:
https://github.com/agemooij/sbt-prompt/issues/10

**Comment by eloots** [comment]
@robinraju Nice find! Will try this out ASAP
