### ISSUE TITLE
Make Studentified repos more useable for Maven projects

### ISSUE THREAD

**Issue by eloots** [eloots/course-management-tools#150]
The idea to use the course management tools to manage Maven based projects has been explored:

- Use a master project with different exercises in the same was as for a Java/Scala project.
- Use `cmt-studentify` to create studentified artifacts where the exercise base folder holds a Maven build definition.
- Students use an sbt session (as in a Java/Scala project) to 'drive' the exercises (using `nextExercise`, `pullSolution`, etc.

This approach works, but it has a few inconveniences due to the way the exercises navigation is managed in the studentified repo.:

- `pullSolution` swaps the complete exercise code state for the complete solution state. This also wipes out tolling files and folders (for example, in IntelliJ, the project .iml folder). In general, this requires a student to reload the project which can be done by a single click, but it is a waste of time).
- `nextExercise` [and friends] works fine, with one potential inconvenience: if the Maven build def changes between exercises, the modified build def will not be loaded by the command

This issue proposes to enhance the tooling to:

- allow for a list of folders in the exercise folder that should be left as-is by `pullSolution`. This list should be defined via configuration using the existing `course-management.conf` mechanism.
- make `nextExercise`, `prevExercise`, `gotoExercise` also pull the Maven build def file. This may actually be as simple as adding it to the `studentify.test-code-folders` config setting.

As a bonus, it may be worth considering dropping the passing of config settings via the `Settings.scala` mechanism and replace it with regular configuration parsing: the `course-management.conf` can be added to the studentified repo as-is (or transformed to another config format if that is easier) and should be read when starting up the sbt project.

**Comment by eamelink** [comment]
I have a clean java implementation of the student command set. I'll change that one to Scala and add it to the repo.

**Comment by eloots** [comment]
Closing this issue as it has been solved in CMT 2.0 @eamelink
