### ISSUE TITLE
Merge authoring tools into a single command.

### ISSUE THREAD

**Issue by eamelink** [eloots/course-management-tools#152]
For historic reasons, `mainadm`, `studentify`, `linearize` and `delinearize` are separate executables. We want to merge them into a single executable, with different subcommands.

At the same time, we want to split the code in two modules: a library with purely the operations, and an SBT part that integrates the library into SBT. This allows the library to also be used outside sbt, for example by the detached mode student client.

This will also reduce duplicate code.

**Comment by eloots** [comment]
That's been done in CMT 2.0 (the command is now `cmta` which uses subcommands. @eamelink
