### ISSUE TITLE
Project can't be loaded on Linux (in sbt, IntelliJ) - courseName vs coursename

### ISSUE THREAD

**Issue by lutzh** [eloots/course-management-tools#57]
When loading the project with sbt or IntelliJ on a case sensitive file system (as is the default in Linux), you'll get an error message:

```
[error] java.io.FileNotFoundException: .../lightbend-training/LAS-E-lightbend-akka-for-scala-expert/.courseName (No such file or directory)
```

The file in the repository is called  `.coursename`, but sbt looks for `.courseName`

**Comment by eloots** [comment]
IIRC, the incorrect case in the `.courseName` was in a specific course from Lightbend. This has probably been fixed in the course master repo for that course. Closing this issue.
