### ISSUE TITLE
Masteradm init expects `exercise` naming

### ISSUE THREAD

**Issue by ennru** [eloots/course-management-tools#75]
As `masteradm -b <masterRepo>` doesn't look at the config file, it doesn't know that folders might have a different naming scheme (eg. `step_`).

**Comment by ennru** [comment]
That's of course the case for all commands that take the repo instead of the config file as parameter.

**Comment by eloots** [comment]
@ennru ACK - `masteradm` command should be reviewed to adapt where needed to take into account the new exercise prefix naming feature.

**Comment by eloots** [comment]
@ennru 

I verified this on a sample project and all possible `mainadm` incantations take into account the `studentify.exercise-project-prefix` setting. Making the `exercise` prefix configurable was done in #66 and I haven't verified if this issue existed in the very first version of the feature. In any case, IMO this can be closed now.

**Comment by ennru** [comment]
Thanks!
