### ISSUE TITLE
Maintain and make available CMT master template repositories

### ISSUE THREAD

**Issue by eloots** [eloots/course-management-tools#92]
Currently, no comprehensive set of CMT master repositories exist. This makes it particularly difficult for anyone who has no experience with the tooling to start using it in anger. At best, one finds an existing CMT project that is modified to suit the needs at hand. Not ideal...

#91 provides a good foundation to fill this gap: the validation master repositories can be created in such a way that they can serve as CMT master repository templates.

Also, we can imagine that we start issuing releases that contain these CMT templates readily usable by anyone wishing to start with CMT.

Alternatively, add a new CMT command, or an option `-init <template name>` to `mainadm`.

**Comment by kyw-iduce** [comment]
Thank you Eric for this, but I have a basic question. I took the sample master and put a couple of exercise. But after studentifying it pullSolution does not bring the solution.  Is pullSolution an alias for nextExercise and pullSolution? 

Thank you

**Comment by eloots** [comment]
@kyw-iduce Hi Kidane!
I'm in the process of updating the documentation which has been untouched for too long a time.
Which of the templates did you use? For sure, this works as it is tested as part of the CI/CD on this project.
The process to utilise one of the templates is to copy it to a new folder outside of the cloned repo.
You should then edit the `course-management.conf` file and remove the line at the end of the file that sets `relative-source-folder`.
Of course, you also need to initialise the template folder as a git repository and commit the current state.
You can then add new exercises by simply cloning a folder and renaming it appropriately (changing the exercise number and description). Note that it is important to follow the naming convention: the exercise number should exactly be 3 digits preceded and followed by an underscore.
Then run `mainadm -b <absolute-path-to-your-new-project>`: this will regenerate the root `build.sbt` file. Test the functionality in the master. Use the sbt `project` command to select an exercise and run/test the code.
Once you're done editing the master, commit your changes.
You can then run `studentify`. Make sure to add the `-dot` option as the templates have been constructed using the assumption.
To clarify the workings of a studentified repo:
- `nextExercise` moves to the next exercise and it automatically does a selective pull-in of the test code for that exercise (you can actually specify where your test code is located in the exercises. Default it pulls in everything under `src/test`). This command also leaves any other code under `src/main` untouched.
- `pullSolution` on the other hand pulls in _all_ the code for the exercise at which you're currently positioned.
Hope this makes things clearer!
